### ISSUE TITLE
Minor highlighting issue with feature list

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#283]
Selecting a feature in a feature list will only highlight the portion of that feature's text which is currently visible on the screen. The remainder of that feature's text turns to black, which makes it unreadable on my screen.

It's a minor issue but as the screenshot shows, it can make it awkward to confirm I have selected the correct result out of several similar variations.

<img width="607" alt="Screenshot 2023-12-20 at 22 22 34" src="https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/8032571/2f050eb9-7e66-46ec-a466-f23189097a35">

**Comment by ldeluigi** [comment]
I tried to experiment with possible fixes but all come at a cost. The current behavior is the best compromise already that doesn't cause weird UX elsewhere. Additionally, this is the behavior that the developers of Django have decided to provide, because the admin UI is auto generated for the most part, including this one.

This will eventually change once we decide to change the theme of the admin dashboard but for now it stays like that, sorry!
