### ISSUE TITLE
Request: Keep features selected between searches

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#319]
We have so many features that it's tricky to search for exactly the ones you're looking for. Editing related features often involves multiple searches.

Current behavior:
Any new feature search removes all selections you've made.

Requested behavior:
A new feature search keeps your current selections, moving them to a new "Selected Features" section above the search results.

**Comment by ldeluigi** [comment]
Unfortunately this can't be implemented by configuration of the django admin framework, and would require a custom view with custom HTML, CSS and maybe JS. In other words, too much time for what's worth.

I can, on the other hand, allow to visualize more than just 100 feature at a time, in order to probably bypass the need to change page.

**Comment by ldeluigi** [comment]
I'm adding the ability to search multiple values with ` | ` separator
