### ISSUE TITLE
Allow Edit of Results in Variant Screen

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#359]
When checking a variant, it does not allow you to edit the results. See below
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/960ac859-be69-4119-b78f-3dfe46064d05)

I understand that I can use Utility combos to get results here, but there's going to be times where I can't make these. For example, doing a utility such as "Altar of Dementia + Infinite sacrifice triggers -> Infinite mill + Infinite self-mill" will almost always be OK. But "Phyrexian Altar + Infinite sacrifice triggers -> Infinite colored mana" will not always work. It will be situational on if the combo uses the mana or not. Therefore, when I generate it using the "Free Sacrifice Outlet - Creature" feature, I need to be able to edit this as appropriate for each combo.

**Comment by ldeluigi** [comment]
Ideally you should be able to figure out a way to define combos that adds Infinite colored mana conditionally

**Comment by ldeluigi** [comment]
In the worst case you can add the result to the generator combo

**Comment by GordonsKitchen** [comment]
I can't think of a way to do this without adding new utility combos for each individual variant when this comes up. This would be very time consuming and also defeats the purpose of generating new variants, since I would have to create unique combos for the utility results anyways. At that point it would be about as easy to create the new variants by hand and not worry about one-off utility combos. If you have an idea on how we can define these results without needing to make unique utilities for each one, that'd be appreciated. It would save us a lot of time

**Comment by ldeluigi** [comment]
> If you have an idea on how we can define these results without needing to make unique utilities for each one, that'd be appreciated. It would save us a lot of time

When I get back from vacation I'll sit down and try my best.

**Comment by GordonsKitchen** [comment]
I added a new utility feature titled "Infinite sacrifice outlet products", which I will add to combos that do not use the products of the sacrifice outlet. This allowed me to create utility combos for those results without every combo that uses those sacrifice outlets having them tacked on. This at least gives us some control until a more permanent solution is released.

This method isn't perfect though. For example, one variant I generated doing this had both "Infinite colored mana" and "Infinite black mana" as results. We usually would just list the colored mana result since it includes black mana. So we will still need a way to remove errant results like that. The best would be to allow us to edit those in created variants, because I'm sure more odd corner cases will pop up and it'll be handy. Otherwise, we may need a way to tell the generator to group those together. Almost like a hierarchy where if something higher on the hierarchy exists, it removes anything below it. (In this case, Infinite colored mana would be above Infinite black mana, and Infinite black mana would be removed).

**Comment by ldeluigi** [comment]
The problem here is that this feature brings in the necesseity to write a lot of code that takes care of preserving the "manual edit of features in variants" between different variant generations.

Variants are supposedly able to get removed and added back, and the operation would drop manually added features.
Instead, if you add manually a feature to a variant by creating a combo that is specific, you get the benefit of reproducibility, customizability (of combo fields that get merged), trace and so on, and the code doesn't need to undergo any change.

A different matter would be to have a new user interface/admin page that **simulates** the ability to edit variants results but under the hood creates new combo.
If you would like to explore that possibility, open a new/different dedicated issue. I'm closing this for now.
