### ISSUE TITLE
Allow Multiple needed Features with the same name In Combo

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#365]
Some combos are going to require us to use multiple cards from a particular feature. For example, using 2 token doublers, using 2 Clones, etc. We will need a way to specify either a quantity or add it multiple times. Then, the program will need to generate each unique combination, of course avoiding using the same card multiple times in a particular variant.

![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/4ddb5371-b805-44f3-92f4-66a440ffaefe)

Example of combo that would use this: https://backend.commanderspellbook.com/admin/spellbook/variantsuggestion/484/change/

**Comment by ldeluigi** [comment]
This is going to take me a long time, but it's a necessary evolution of the current variant generator. I'll develop this feature later this year, when I find the time required for this.

**Comment by ldeluigi** [comment]
Design notes:
1. If feature needed in combos get an `amount` (small integer field), then implicitly produced features should get that too, resulting in the necessity to turn produced features into inlines instead of a table
2. The code that generates variant will probably increase in complexity by a lot: it will have to take into account amounts to satisfy feature requirements for each combo, computing every possible combination of recipes that will have each requirement amount satisfied.
3. The minimal set of sets, which is a TrieSet under the hood, will probably become obsolete, resulting in really worse performances for complex combo networks (this needs testing)
