### ISSUE TITLE
[Proposal] Grouping Features Together

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#366]
This is a proposal for a future enchantment. It would be useful to have a way to create a group of features with a common theme for use in creating utility combos. For example, I could create a group titled "Infinite mana", and include in the group any feature dealing with infinite mana, including: Infinite colored, Infinite colorless, etc. Then, I could make one utility combo and cover all the features versus needing to make a separate one for each infinite mana result. I would imagine this would work similarly to the Features page, where we can select features in the group and add new ones as needed.

So if I make the combo: "Staff of Domination + Infinite mana -> Infinite card draw"
The program will take this and translate it into the individual combos. So that would become "Staff of Domination + Infinite colored mana", "+Infinite colorless mana" and so on for each feature in the group. I'm not sure if it would be easiest to do this when a utility is created, or if it is easiest to do when generating variants. I'll leave that to your discretion.

Currently, I would have to make an individual feature for each distinct mana result. This is cumbersome and creates a bunch of utility features that all do the same thing.

**Comment by ldeluigi** [comment]
Creating a "group" that includes feature B, C, D, ... under a common hood called A, as far as I understand, is the same as creating n combos in the form "B -> A", "C -> A", "D -> A", right?

In that case, the work to define those combos must be done only once, then you can use A as needed feature in any combo you like from that point onwards.

As a result, I don't think that overcomplicating the model would be beneficial, because the code that generates variants already pushes the limit of affordable complexity for this one man project.

If you agree, I'd like to close this issue as not planned.
