### ISSUE TITLE
Combo Changelog didn't post all variants

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#413]
<img width="848" alt="Screenshot 2024-05-06 at 13 56 17" src="https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/8032571/c091dc4f-cccc-406b-8287-caac7fd151fe">

I replaced Selvala in a combo with Bighorner Rancher.

Two of the resulting variants needed extra tweaks, so I edited them and marked them OK individually. These are the two the Combo Changelog bot posted above.

I then marked the other OK all at once, and the bot didn't post to the changelog.

P.S. let me know if changelog bot issues should be posted elsewhere.

**Comment by thirdpolice** [comment]
Marking 3 variants OK at once — posted to changelog as expected

Marking 53 variants OK at once — no changelog post

So this may be affected by # of variants.

**Comment by GordonsKitchen** [comment]
I had this same issue with 29 variants. Deloo theorized it could be hitting Discord's character limit and not posting (I believe 2,000 is the normal character limit, or 4,000 with Nitro). Messages should be made separately so that it doesn't hit this limit (either by counting the characters and dividing that way, or perhaps capping a message at 10 combos). 

Link to the job I am referring to: https://backend.commanderspellbook.com/admin/spellbook/job/14125/change/
Note that it says "Success" but no message was posted. This should also probably be addressed, if possible.

**Comment by ldeluigi** [comment]
I confirm it was the character limit being hit. It will be fixed in the next release
