### ISSUE TITLE
Improve Scryfall query syntax

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#429]
It would be really nice to get some added support for Scryfall query syntax in the templates. Some of the restrictions make it very difficult (or straight up impossible) to make certain templates.

The first thing is that these error messages should help the editor figure out what is wrong, rather than the editor having to trial and error removing stuff to figure it out:
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/97813519/71c65b18-b3c3-46b0-a76b-ec97d3e7f30a)
Simply saying "Invalid syntax" doesn't help us determine what exactly is invalid. I would assume the program knows what is wrong because it knows to throw the error, so that error can be displayed to make fixing it easier. For example, "Error: Unknown function 'test:'". This could be done by having an additional message and/or by highlighting what is wrong in the query text box.

Some other things I've noticed that I would like to make life easier:
1. Automatically remove format (f:) in the syntax. I always add "f:edh" when making a query on Scryfall so I can accurately see what will show on the site. Almost every single time I forget to remove it and get an error about it. It'd be nice if either the code can just ignore it (because having both f:edh and legal:commander doesn't change anything) or just remove it entirely.
2. Add some limited regex support. I understand this may be complicated, but some templates can benefit greatly from this. For example, the expression "-mana:/[wubrg]/" finds all cards that don't have a colored mana symbol in its cost, which is very important for affinity combos or Animar combos. And if I need to use that in a template, there sometimes is no other way given the constraints of the syntax to make it work without using the regular expression.
3. Possibly add some of the shortcuts, like "kw:" for "keyword:"

**Comment by ldeluigi** [comment]
I'm answering some points you highlighted:

- Error messages can't be improved as you ask because the validation of the query is done by a gigantic regular expression by the backend, which runs as a black box basically
- Removing f:??? will be implemented
- Regex support is already present: 
![image](https://github.com/SpaceCowMedia/commander-spellbook-backend/assets/44567586/6c71b9a9-b829-4b6b-a3ed-b70c4780c8ec)
but it's disabled for `mana` and for numeric variables, such as `mv|manavalue|power|pow|toughness|tou|pt|powtou|loyalty|loy`, because almost always the same thing can be written without regular expression. For example your query finds all the cards that don't cost any color, which can be written as `-mana:{W} -mana:{U} -mana:{B} -mana:{R} -mana:{G} -type:land`. The advantage is that when scryfall interprets the query is faster and explains it better at the top of the screen
- Shortcuts are already present, I simply missed kw. I'm adding it
