### ISSUE TITLE
Proposal: taggable qualities for single cards in a feature's "produced by cards" section

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#462]
Creating many comprehensive utility features has the potential to make future CSB editing much smoother and easier, but there are three main technical barriers to implementing this system fully:

- A combo that uses a utility feature to generate 10 variants will often produce several “Not Working” variants, and several more that need to be edited for specific prereqs, steps, etc. This can be a major editor time sink.
- As the list of utility features grows, it becomes harder to keep track of which ones exist, what they’re called, and how they are linked together to produce specific results. This will make it much harder to train new editors.
- Choosing how exactly to implement a utility feature or group of similar utility features is arbitrary, and decisions made now could end up causing systemic clunkiness that’s difficult to fix later on, especially as Magic inevitably adds new mechanics that care about new things.

We can solve all three problems if we introduce a “tag” system that adds further categorization to cards within the “produced by” section of a feature.

For example, in the current system, Clone, Heat Shimmer, and Lazav the Multifarious are three Clone-like effects, but there is no perfect way to handle them. Many combos can use all three versions of this effect, but many others need to separate them because they rely on card type, token-ness, or ETB effects.

With a tag system, we could create just one utility feature, “Copy a Creature” and include this extra information in tags:
- Clone : ETBs as creature
- Heat Shimmer: Creates token copy
- Lazav the Multifarious: Becomes a copy on the field

When creating or editing a combo that requires a feature, editors would then interact with a “card qualities” or "card tags" section. The best approach is probably to have all cards included by default, but support multiple use cases:
- Any of N specific qualities are required for the combo.
- All of N specific qualities are required for the combo.
- Any of N specific qualities invalidate the combo; no variants will be generated from cards with those qualities

Editors would definitely need the ability to add additional tags to a feature after creation. In the above example editors would likely discover they need to edit in new tags like “Sac at EoT” or “Bypasses legend rule” as they wrote more copying combos.

I’ve described these qualities as existing within a specific feature’s info, which I think is best from an editing perspective. Qualities directly tagged to the card itself would probably create UX challenges.

=====
Related features to consider:

- Whether or not this specific proposal gets implemented, it would be very helpful to support a code-like way to restrict cards using qualities obtainable from Scryfall data. For example, the ability to restrict a required feature by mana value just by typing "MV<3" in the combo creation tool would be extremely helpful. (Of course this would only affect variants where that feature is produced by a single card.)

- It may also eventually be useful to allow a nested hierarchy of features (e.g. Copy a permanent includes copy a creature includes copy a green creature...), since even this system will eventually get bloated. But it is already possible to set up combo generation to work this way so I mention this only as an ambitious future wish.

**Comment by ldeluigi** [comment]
I'll contribute by addressing your points with my insights.

> A combo that uses a utility feature to generate 10 variants will often produce several “Not Working” variants, and several more that need to be edited for specific prereqs, steps, etc. This can be a major editor time sink.

Fair. My idea during design would have been the use of specific features that describe specific MtG effects such that combo using them already almost always know they work and what they achieve.

> As the list of utility features grows, it becomes harder to keep track of which ones exist, what they’re called, and how they are linked together to produce specific results. This will make it much harder to train new editors.

This is totally true, and I've always thought it was a compromise to allow the automation of generation. From my point of view, every magic player has all those "features" somehow coded in their head when they simulate magic plays by thinking, and to me it's more of a matter of finding a common convention to identify those patterns rather than avoiding the complexity by having few features and more manual labor.

> Choosing how exactly to implement a utility feature or group of similar utility features is arbitrary, and decisions made now could end up causing systemic clunkiness that’s difficult to fix later on, especially as Magic inevitably adds new mechanics that care about new things.

This is a very good point. I know right. Maintaing such a big magic related feature set is almost a full time worth of a "job", but having the Python code do it instead is simply even worse, because a code change is way more expensive that a manipulation of our feature dataset. The ideal may be in the improvement of our user experience with the definition and identification of the best feature needed in a combo, as you are further delving into later.

> We can solve all three problems if we introduce a “tag” system that adds further categorization to cards within the “produced by” section of a feature.

> For example, in the current system, Clone, Heat Shimmer, and Lazav the Multifarious are three Clone-like effects, but there is no perfect way to handle them. Many combos can use all three versions of this effect, but many others need to separate them because they rely on card type, token-ness, or ETB effects.
> 
> With a tag system, we could create just one utility feature, “Copy a Creature” and include this extra information in tags:
> 
> Clone : ETBs as creature
> Heat Shimmer: Creates token copy
> Lazav the Multifarious: Becomes a copy on the field
> When creating or editing a combo that requires a feature, editors would then interact with a “card qualities” or "card tags" section. The best approach is probably to have all cards included by default, but support multiple use cases:
> 
> Any of N specific qualities are required for the combo.
> All of N specific qualities are required for the combo.
> Any of N specific qualities invalidate the combo; no variants will be generated from cards with those qualities

This is basically what I call "feature pattern matching": in principle, you have few features, such as "Clone", and you define some attributes in the relationship between a card or a combo and a produced feature, such as "ETBs as creature", which can be present or absent. Then, in combos, needed features have some requirements expressed in needed attributes, which can be present or absent, representing a pattern that must be matched with produced features in order to work in generation. With the "Clone" feature example, if our database is missing a "Clone" producer with the attribute "ETBs as a creature" the generation cannot move on that path.

These attributes is what you are calling "~card~ qualities", or "~card~ tags". I think I can implement something for this.
I'll give it a try sometime.


Moving on:

> Related features to consider:
> 
> Whether or not this specific proposal gets implemented, it would be very helpful to support a code-like way to restrict cards using qualities obtainable from Scryfall data. For example, the ability to restrict a required feature by mana value just by typing "MV<3" in the combo creation tool would be extremely helpful. (Of course this would only affect variants where that feature is produced by a single card.)

This, in turn, is unexpectedly way harder, because the current feture system is not tied with card replacement, and instead works fine by replacing features with both cards and combos, to which card restrictions hardly apply well.

> It may also eventually be useful to allow a nested hierarchy of features (e.g. Copy a permanent includes copy a creature includes copy a green creature...), since even this system will eventually get bloated. But it is already possible to set up combo generation to work this way so I mention this only as an ambitious future wish.

This is also incompatible with the current system because a hierarchy can have any depth and there is no right UI to display that. Relying on a naming convention and the combo system is the only way I see possible for inter-feature dependencies.

**Comment by thirdpolice** [comment]
Thanks for the reply, Deloo.

I agree that our focus should be improving the editor's UX and philosophical approach and not trying to automate card/feature classification.

I would say it is practically impossible to create a common naming convention that is simple enough on its own for onboarding new editors, especially at some future date when the current team leaves the project and someone else tries to take on the job. For that to be possible, we need to rely on UX as well, making it as easy as possible for editors to view the relationships between similar features and their use in combos. Tags would make this much easier to grok than a group of similar features and a web of interacting utility combos.

> it's more of a matter of finding a common convention to identify those patterns rather than avoiding the complexity by having few features and more manual labor.

I would say an attribute system would require significantly less labor than a high-feature-count system.

Perhaps even more importantly, an attribute-assignment mistake is much easier to notice and correct because the relevant info appears on a single page. In the current system it is difficult to notice a missing card-feature relationship because it requires someone to compare the list of produced features on one page with a feature search result on a separate page.

Anyway, I appreciate you giving attributes a try and happy to discuss further.

We can disregard the 'related features' for the time being given those challenges.

**Comment by GordonsKitchen** [comment]
I highly support being able to select what cards from a feature we want for a particular generation, whether that be via tags or a simple "Check to select" system. It will cut down on editing of variants, "Not Working" variants and make the generation cleaner. I would say that all cards in a feature should be selected to generate by default and then manually unselected and/or excluded via tags. The Scryfall narrowing would be nice, but if we can get the check/select implemented that would be good enough for now - at least for me.

**Comment by thirdpolice** [comment]
Yes, I agree with that approach. Every step along that path would make a difference (check to select -> tags -> scryfall narrowing or other advanced features) but the first one alone would be a great improvement.On 30 Jun 2024, at 21.05, Gordon ***@***.***> wrote:﻿
I highly support being able to select what cards from a feature we want for a particular generation, whether that be via tags or a simple "Check to select" system. It will cut down on editing of variants, "Not Working" variants and make the generation cleaner. I would say that all cards in a feature should be selected to generate by default and then manually unselected and/or excluded via tags. The Scryfall narrowing would be nice, but if we can get the check/select implemented that would be good enough for now - at least for me.
