### ISSUE TITLE
Combos Tab Queries Not Filtering Correctly

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#495]
It doesn't appear that the combos tab is filtering quite correctly. See below:

![image](https://github.com/user-attachments/assets/c918e1f7-e8e1-493a-896b-477e511a85ca)
Link here: https://backend.commanderspellbook.com/admin/spellbook/combo/?o=6&q=doubler+-+tokens

The combo should not show, because nowhere is "Doubler - Tokens" listed. Since the combos page looks for the entire query in one object, this shouldn't show from what I gather.

**Comment by ldeluigi** [comment]
![image](https://github.com/user-attachments/assets/8e536349-5432-4537-b76f-001656a3b3ee)
The issue comes from the fact that your link is sorting results by ascending updated date.
If you remove the ordering you get the correct result instead:
https://backend.commanderspellbook.com/admin/spellbook/combo/?q=doubler+-+tokens
