### ISSUE TITLE
Force Generator Combos to Have 1+ Produced Feature(s)

### ISSUE THREAD

**Issue by GordonsKitchen** [SpaceCowMedia/commander-spellbook-backend#508]
![image](https://github.com/user-attachments/assets/09701313-b8fb-4807-9faf-38a4c428275d)

The backend currently allows generator combos to not have a listed produced feature. Generator combos will always need to have 1+ produced feature(s). I do not want to force all combos to have one listed, because of drafts and utilities that don't always need them.

**Comment by ldeluigi** [comment]
The fact that generator combos must have a result is an editor convention, but in theory a generator combos could be composed of a set of features that alone are sufficient to generate variants with all the necessary results, without adding a new one on top.

In addition, I can't implement this feature because Django unfortunately does not allow to cross-check fields of a Combo (in this case the kind) together with the related entities (in this case the produced features).

If you agree I'd like to close this issue
